### ISSUE TITLE
推出去的视频颜色不对

### ISSUE THREAD

**Issue by 27988301** [ThinkKeep/EvilsLive#24]
rtmp推流成功，收视端接收到的视频**_ 颜色显示成灰色*_*能看看吗。

**Comment by 27988301** [comment]
int res = evils_live_send_yuv420(index, data, size, width_, height_);这个方法转的时候能否修改下呢，我不会改，能看看吗/,目前来看应该在这里转的时候颜色出了异常，变成了灰色

**Comment by longxx007** [comment]
是的，正在改

**Comment by jasonim** [comment]
@27988301 问题已经修正， 你再看看

**Comment by 27988301** [comment]
好的，在下载

**Comment by 27988301** [comment]
so ku，颜色是对了，还有一个问题，我改成720p，完了本地预览都是黑屏，是不支持720p吗？ 或者更高的分辨率，帮忙看看，感谢，这个你们不收费吗？

**Comment by jasonim** [comment]
@27988301 这个我到时候测试一下， 目前不考虑收费，主要提供大家来学习的，还有很多不完善的地方

**Comment by jasonim** [comment]
@27988301 你也可以单独提一个issue
