### ISSUE TITLE
修改分辨率

### ISSUE THREAD

**Issue by 27988301** [ThinkKeep/EvilsLive#26]
我改成720p，完了本地预览都是黑屏，是不支持720p吗？ 或者更高的分辨率，支持吗？

**Comment by 27988301** [comment]
1，还有这个分辨率的问题，是否能够多个分辨率，来选择。
2，码流提供几个，比如512,1024，之类的来做选择，体验会更好哦。

**Comment by 27988301** [comment]
比较急，支持720p的分辨率什么时候能出来。感谢感谢

**Comment by jasonim** [comment]
@27988301 分辨率的已经改好， 正在测试，还在优化代码，今天能好

**Comment by jasonim** [comment]
@27988301 720P分辨率可以了， 你可以试试， 多码率下一步支持

**Comment by 27988301** [comment]
我怎么在外层设置这个分辨率呢，看代码也是自己识别的嘛

**Comment by 27988301** [comment]
this.videoresolution = E720P;
OK，能识别720p了

**Comment by 27988301** [comment]
choosePreviewSize这个方法中，
        if (size == null) {
            size = new Size(Defines.EvideoResolution.E640P.getWidth(), Defines.EvideoResolution.E640P.getHeight());
        }
这句话有点疑惑，配置中设置了E720P，这个size是有值的，为什么还走了这句？百思不得其解啊

**Comment by jasonim** [comment]
@27988301 这个异常处理的， 防止viewResolution == null 的情况， 分辨率用户可配的， 传入什么值都有可能
