### ISSUE TITLE
修改码流

### ISSUE THREAD

**Issue by 27988301** [ThinkKeep/EvilsLive#28]
分辨率是能修改了，但是码流跟不上，延迟的显现明显 高了。
我用的720p，现在的码流是512，明显不够用，希望测试一下720p的延迟，画质，卡顿的显示，是否存在。合理的分配码流。感谢感谢

**Comment by longxx007** [comment]
现在加了x264多线程的支持，可以再尝试一下720p，看看延迟、卡顿的情况
